### ISSUE TITLE
Dataset info and checkpoints 

### ISSUE THREAD

**Issue by MahdiMohseni0033** [mihirp1998/AlignProp#1]
Thank you for your valuable contributions. Could you kindly provide some details about the dataset used in this project repository? Additionally, could you also share any checkpoints or model weights associated with this project?

**Comment by mihirp1998** [comment]
Datasets are the prompts in this folder: https://github.com/mihirp1998/AlignProp/tree/main/assets
Just a set of prompts in the ".txt" files basically.

Yes i'll opensource the weights in a few days.

**Comment by mihirp1998** [comment]
I have open-sourced the HPS and Aesthetic checkpoints.
