### ISSUE TITLE
run the aesthetic_scorer.py

### ISSUE THREAD

**Issue by xinli2008** [mihirp1998/AlignProp#11]
nice job! I want to use the aesthetic_scorer.py  to test the aesthetic scorer about my images.
But i came across some problems, can you give me some useful advice?

code:
![image](https://github.com/mihirp1998/AlignProp/assets/71311087/336ed32f-b78d-461c-91b6-65502efcd605)
![image](https://github.com/mihirp1998/AlignProp/assets/71311087/ab2ec0df-9538-4cf5-acab-48cb5fce8c67)

the code is wrong prehaps beacuse of the input_image format.
can you tell me what should i process the image before generate the aesthetic scorer

**Comment by mihirp1998** [comment]
you can follow this function: 

https://github.com/mihirp1998/AlignProp/blob/b519ad87484cdafcfca761013928e59a3fac0923/main.py#L89
