### ISSUE TITLE
DRaFT paper

### ISSUE THREAD

**Issue by yinanyz** [mihirp1998/AlignProp#12]
It looks like DRaFT ([DIRECTLY FINE-TUNING DIFFUSION MODELS ON DIFFERENTIABLE REWARDS)](https://arxiv.org/pdf/2309.17400.pdf) has a similar idea, and I'm wondering what're the main differences between your approaches. Thanks!

**Comment by mihirp1998** [comment]
Yes this is indeed a concurrent work.

In terms of code the difference should be minor. 

i) We do randomized truncated backprop however they do just truncated backprop. Although our code has the option to do truncated backprop, you can simply set randomized flag to be False.

ii) They sample many noise samples, however in our code we sample a single noise sample.
