### ISSUE TITLE
Crashes when saving checkpoints

### ISSUE THREAD

**Issue by Metal079** [mihirp1998/AlignProp#3]
Managed to get the training going and when it tried to save the checkpoint it crashed. 

used accelerate launch main.py --config config/align_prop.py:hps

> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.11it/s]
> I1009 13:38:00.045277  6908 logging.py:47] Logging
> I1009 13:38:00.047276  6908 logging.py:47] loss: 0.00727081298828125, rewards: 0.27294921875
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [1:13:43<00:00, 17.28s/it]
> I1009 13:38:46.315140  6908 logging.py:47] Saving current state to logs\rare-jazz-12\checkpoints\checkpoint_0
> Traceback (most recent call last):
>   File "C:\Users\metal\OneDrive\Documents\programming\AlignProp\main.py", line 610, in <module>
>     app.run(main)
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\absl\app.py", line 308, in run
>     _run_main(main, args)
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\absl\app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "C:\Users\metal\OneDrive\Documents\programming\AlignProp\main.py", line 601, in main
>     accelerator.save_state()
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\accelerator.py", line 2230, in save_state
>     hook(self._models, weights, output_dir)
>   File "C:\Users\metal\OneDrive\Documents\programming\AlignProp\main.py", line 272, in save_model_hook
>     output_splits[1] = wandb.run.name
> IndexError: list assignment index out of range
> wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
> wandb:
> wandb: Run history:
> wandb:            epoch ▁▁
> wandb:     eval_rewards ▁█
> wandb: eval_rewards_std ▁█
> wandb:      inner_epoch ▁█
> wandb:             loss █▁
> wandb:          rewards ▁█
> wandb:
> wandb: Run summary:
> wandb:            epoch 0
> wandb:     eval_rewards 0.27075
> wandb: eval_rewards_std 0.02486
> wandb:      inner_epoch 255
> wandb:             loss 0.00727
> wandb:          rewards 0.27295
> wandb:      rewards_std nan
> wandb:
> wandb:  View run rare-jazz-12 at: https://wandb.ai/metal/align-prop/runs/z7uiknc7
> wandb:  View job at https://wandb.ai/metal/align-prop/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEwNTIwNTg1NA==/version_details/v5
> wandb: Synced 6 W&B file(s), 4 media file(s), 2 artifact file(s) and 0 other file(s)
> wandb: Find logs at: .\wandb\run-20231009_122444-z7uiknc7\logs
> Traceback (most recent call last):
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\metal\miniconda3\envs\alignprop\Scripts\accelerate.exe\__main__.py", line 7, in <module>
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\launch.py", line 915, in launch_command
>     simple_launcher(args)
>   File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\launch.py", line 578, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['C:\\Users\\metal\\miniconda3\\envs\\alignprop\\python.exe', 'main.py', '--config', 'config/align_prop.py:hps']' returned non-zero exit status 1.
> 
> (alignprop) C:\Users\metal\OneDrive\Documents\programming\AlignProp>

**Comment by mihirp1998** [comment]
Oh sorry i think my naming conventions are very linux based.

I think for windows `output_splits = output_dir.split("/")` this shouldn't be the right way of splitting 

rather it would be  `output_splits = output_dir.split("\")` i expect.

I ll write a seperate patch for windows later this week, although let me know if the above soln works

**Comment by Metal079** [comment]
> Oh sorry i think my naming conventions are very linux based.
> 
> I think for windows `output_splits = output_dir.split("/")` this shouldn't be the right way of splitting
> 
> rather it would be `output_splits = output_dir.split("\")` i expect.
> 
> I ll write a seperate patch for windows later this week, although let me know if the above soln works

No luck, it crashes immediately if I change it to \\, I also tried 

        output_splits = output_dir.split("\\") or output_splits = output_dir.split(r"/") 

but that produces this error

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:19<00:00, 19.94s/it]
Traceback (most recent call last):
  File "C:\Users\metal\OneDrive\Documents\programming\AlignProp\main.py", line 610, in <module>
    app.run(main)
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\metal\OneDrive\Documents\programming\AlignProp\main.py", line 598, in main
    assert accelerator.sync_gradients
AssertionError
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:  View run dulcet-firebrand-19 at: https://wandb.ai/metal/align-prop/runs/saf7bdr7
wandb:  View job at https://wandb.ai/metal/align-prop/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEwNTIwNTg1NA==/version_details/v8
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20231009_141508-saf7bdr7\logs
Traceback (most recent call last):
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\metal\miniconda3\envs\alignprop\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\launch.py", line 915, in launch_command
    simple_launcher(args)
  File "C:\Users\metal\miniconda3\envs\alignprop\lib\site-packages\accelerate\commands\launch.py", line 578, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\metal\\miniconda3\\envs\\alignprop\\python.exe', 'main.py', '--config', 'config/align_prop.py:hps']' returned non-zero exit status 1.

For reference, to test this i set the config to 1, just in case thats why
config = set_config_batch(config, total_samples_per_epoch=1,total_batch_size= 128, per_gpu_capacity=1)

**Comment by Metal079** [comment]
> Oh sorry i think my naming conventions are very linux based.
> 
> I think for windows `output_splits = output_dir.split("/")` this shouldn't be the right way of splitting
> 
> rather it would be `output_splits = output_dir.split("\")` i expect.
> 
> I ll write a seperate patch for windows later this week, although let me know if the above soln works

Wait nvm I got it to save by doing output_dir.split("\\\")  as well as

    config = set_config_batch(config, total_samples_per_epoch=2,total_batch_size= 1, per_gpu_capacity=1)

thank you for the help finding the issue.

though quick question,  pytorch_lora_weights.bin can be loaded just fine by diffusers or auto1111 correct?
![image](https://github.com/mihirp1998/AlignProp/assets/7731400/018c4d8b-3e5f-4dae-84ba-45b4a5faf90e)

**Comment by mihirp1998** [comment]
I'm assuming it's fixed, btw for hps reward function i dont think you need to run for all 200 epochs, i think probably in 55 epochs or so  it should converge.  I'll soon update this in the main repo with it's config.
