### ISSUE TITLE
question about accelerate

### ISSUE THREAD

**Issue by Xerxemi** [mihirp1998/AlignProp#7]
Is there a technical reason why accelerate must be ==0.17.0?

Tested it with latest accelerate and it at least seems to run. Does it break part of the code?

**Comment by mihirp1998** [comment]
There seems to be some bug in accelerator.save_state() when using versions higher than 0.17.0,  you can find more details here:

https://github.com/kvablack/ddpo-pytorch/issues/13#issuecomment-1714943134
